### ISSUE TITLE
JOSS Review: GroundwaterDupuitPercolator, address discoverability

### ISSUE THREAD

**Issue by kbarnhart** [landlab/landlab#1108]
In the [JOSS Review Issue](https://github.com/openjournals/joss-reviews/issues/1935) @rreinecke has made the following comment regarding discoverability of the tests, documentation, notebooks, dependencies for the this component. 

> Concerning the submodule I strongly disagree but that is something you need to decide and will not be part of this review. Nevertheless, I already have a problem in verifying the functionality of the software as I cannot find according unit tests (and how to run them). If they are somewhere else in the project please add a detailed description to your repository e.g. a list of submodules etc.. Please also explain there where to find which software component. I'm aware that there is another official Landlab page but as my time, and the time of the other reviewer and of course potential future users, is limited please consider to extend your readme. Also install instructions are missing together with a list of dependencies. Furthermore, did you implement a simple example model which demonstrates the capabilities of the new package? If so where? And where do I find the according documentation?

I will address this issue on a forthcoming Pull Request.

**Comment by kbarnhart** [comment]
I've created two PRs to address this issue.

First, #1110 updates core landlab documentation regarding installation, tests, and dependencies. 

Second, #1112 updates the submodule Readme. 

Once these two PRs are merged, I'll ping @rreinecke to asses whether we have addressed his concerns, or if there are still outstanding issues that need to be addressed on this point.

**Comment by kbarnhart** [comment]
@rreinecke -- In discussion with @DavidLitwin we realize that we are not sure what you mean by:

> Please also explain there where to find which software component.

Could you clarify so we can make sure to address this aspect of your comment.

**Comment by rreinecke** [comment]
@kbarnhart Certainly. I'm referring to the main README in the landlab project. I know this review is for the groundwater component only, but as you choose to maintain it in this repository my comments will of course also address possible issues with the landlab project itself.

I'm missing a comprehensible README that:
* Tells me how to install the software
* What the dependencies are
* Were to find examples
* Maybe a short example
* How to run the tests
* Guides me through the package structure of the project
* Where to find the extended documentation
* And tells me who is responsible and how to contribute

I think everything is somewhere in your project and probably on your homepage but it is very cumbersome to find in the gitlab repository (which is under review not your homepage). Please revise the main README. They are many other github projects that do a great job in providing the information mentioned above. Maybe checkout other landing pages to improve yours.

**Comment by kbarnhart** [comment]
@rreinecke thanks for clarifying. I'll re-ping you here when I've revised.

**Comment by kbarnhart** [comment]
@DavidLitwin could you look through the changes that I've made to the readme and the docs and verify that I've addressed @rreinecke 's concerns?

**Comment by DavidLitwin** [comment]
@kbarnhart I think it looks good in general. A few notes on the groundwater readme:
- the word "markdown" appears at the beginning of the document, is that supposed to be there?
- can the TODO for requirements be updated now?
- I'm still not sure we've satisfied the request to know where unit tests live. I will admit, with the new LL2.0 arrangement, it took me a second as well to find them in the testing folder. Do you think we should include more explicit directions on where to find them, or is it sufficient to give instructions on how to run them?

**Comment by kbarnhart** [comment]
@rreinecke I've now updated the main and component readme, as well as the documentation in response to your comments. 

In many cases I've provided links into our more comprehensive documentation (hosted at https://landlab.readthedocs.io/). This is based on experience that duplicated information is difficult to maintain.

If these changes are insufficient, please indicate what needs improving and one of the manuscript authors will address the remaining improvements.

**Comment by rreinecke** [comment]
Thank you. This is much more comprehensible now. Of course there is always a trade of in duplicating information but I think this makes the project much more discoverable now.

I have to agree though with @DavidLitwin that the test structure could be somewhat different. But that is something out of the scope of this review. Before closing this: Am I correct that this is the only test file for the submitted component? landlab/landlab/tests/components/groundwater/test_dupuit_percolator.py

**Comment by kbarnhart** [comment]
@rreinecke thanks for your comments on the readme/docs. I'll let you close this issue.

Regarding the location of tests for this component: 
- The docstrings for the component (in the source code)
- The unit tests within `landlab/landlab/tests/components/groundwater/`

In addition, our continuous integration includes running all the notebooks and asserting that they run without error. This isn't such as strict test because we don't enforce any requirements on the output values (other than they are not errors).

Regarding test structure. I agree that it is beyond the scope of the review. Our reason for choosing this structure was so that our binary distributions don't include the unit test files.

**Comment by rreinecke** [comment]
Thank you! If issues with the tests arise I will open a separate ticket. This has been addressed sufficiently.

**Comment by rreinecke** [comment]
as a side-note @DavidLitwin the tests are very nicely described and documented! A pleasure to read. Could always be extended in the future but to this point great addition to the rest of the tests. I've already recommended this project to some colleagues.

**Comment by kbarnhart** [comment]
@rreinecke thanks for letting me know you can't close it. closing.

**Comment by DavidLitwin** [comment]
@rreinecke Thank you for the feedback on the tests! A good of thought went into them over several months.
